// Generated by gencpp from file optitrack_ros/abort_activityRequest.msg
// DO NOT EDIT!


#ifndef OPTITRACK_ROS_MESSAGE_ABORT_ACTIVITYREQUEST_H
#define OPTITRACK_ROS_MESSAGE_ABORT_ACTIVITYREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace optitrack_ros
{
template <class ContainerAllocator>
struct abort_activityRequest_
{
  typedef abort_activityRequest_<ContainerAllocator> Type;

  abort_activityRequest_()
    : activity(0)  {
    }
  abort_activityRequest_(const ContainerAllocator& _alloc)
    : activity(0)  {
  (void)_alloc;
    }



   typedef uint32_t _activity_type;
  _activity_type activity;





  typedef boost::shared_ptr< ::optitrack_ros::abort_activityRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::optitrack_ros::abort_activityRequest_<ContainerAllocator> const> ConstPtr;

}; // struct abort_activityRequest_

typedef ::optitrack_ros::abort_activityRequest_<std::allocator<void> > abort_activityRequest;

typedef boost::shared_ptr< ::optitrack_ros::abort_activityRequest > abort_activityRequestPtr;
typedef boost::shared_ptr< ::optitrack_ros::abort_activityRequest const> abort_activityRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::optitrack_ros::abort_activityRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::optitrack_ros::abort_activityRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace optitrack_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'optitrack_ros': ['optitrack_ros/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::optitrack_ros::abort_activityRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::optitrack_ros::abort_activityRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::optitrack_ros::abort_activityRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::optitrack_ros::abort_activityRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::optitrack_ros::abort_activityRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::optitrack_ros::abort_activityRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::optitrack_ros::abort_activityRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bbd20bba9542755cfbf3efd56184eaeb";
  }

  static const char* value(const ::optitrack_ros::abort_activityRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbbd20bba9542755cULL;
  static const uint64_t static_value2 = 0xfbf3efd56184eaebULL;
};

template<class ContainerAllocator>
struct DataType< ::optitrack_ros::abort_activityRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "optitrack_ros/abort_activityRequest";
  }

  static const char* value(const ::optitrack_ros::abort_activityRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::optitrack_ros::abort_activityRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
uint32 activity\n\
";
  }

  static const char* value(const ::optitrack_ros::abort_activityRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::optitrack_ros::abort_activityRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.activity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct abort_activityRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::optitrack_ros::abort_activityRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::optitrack_ros::abort_activityRequest_<ContainerAllocator>& v)
  {
    s << indent << "activity: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.activity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPTITRACK_ROS_MESSAGE_ABORT_ACTIVITYREQUEST_H
