// Generated by gencpp from file optitrack_ros/abort_activity.msg
// DO NOT EDIT!


#ifndef OPTITRACK_ROS_MESSAGE_ABORT_ACTIVITY_H
#define OPTITRACK_ROS_MESSAGE_ABORT_ACTIVITY_H

#include <ros/service_traits.h>


#include <optitrack_ros/abort_activityRequest.h>
#include <optitrack_ros/abort_activityResponse.h>


namespace optitrack_ros
{

struct abort_activity
{

typedef abort_activityRequest Request;
typedef abort_activityResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct abort_activity
} // namespace optitrack_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::optitrack_ros::abort_activity > {
  static const char* value()
  {
    return "f1ec71d84e024b77cbdc293016ea6480";
  }

  static const char* value(const ::optitrack_ros::abort_activity&) { return value(); }
};

template<>
struct DataType< ::optitrack_ros::abort_activity > {
  static const char* value()
  {
    return "optitrack_ros/abort_activity";
  }

  static const char* value(const ::optitrack_ros::abort_activity&) { return value(); }
};


// service_traits::MD5Sum< ::optitrack_ros::abort_activityRequest> should match 
// service_traits::MD5Sum< ::optitrack_ros::abort_activity > 
template<>
struct MD5Sum< ::optitrack_ros::abort_activityRequest>
{
  static const char* value()
  {
    return MD5Sum< ::optitrack_ros::abort_activity >::value();
  }
  static const char* value(const ::optitrack_ros::abort_activityRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::optitrack_ros::abort_activityRequest> should match 
// service_traits::DataType< ::optitrack_ros::abort_activity > 
template<>
struct DataType< ::optitrack_ros::abort_activityRequest>
{
  static const char* value()
  {
    return DataType< ::optitrack_ros::abort_activity >::value();
  }
  static const char* value(const ::optitrack_ros::abort_activityRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::optitrack_ros::abort_activityResponse> should match 
// service_traits::MD5Sum< ::optitrack_ros::abort_activity > 
template<>
struct MD5Sum< ::optitrack_ros::abort_activityResponse>
{
  static const char* value()
  {
    return MD5Sum< ::optitrack_ros::abort_activity >::value();
  }
  static const char* value(const ::optitrack_ros::abort_activityResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::optitrack_ros::abort_activityResponse> should match 
// service_traits::DataType< ::optitrack_ros::abort_activity > 
template<>
struct DataType< ::optitrack_ros::abort_activityResponse>
{
  static const char* value()
  {
    return DataType< ::optitrack_ros::abort_activity >::value();
  }
  static const char* value(const ::optitrack_ros::abort_activityResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OPTITRACK_ROS_MESSAGE_ABORT_ACTIVITY_H
