// Generated by gencpp from file optitrack_ros/body_list.msg
// DO NOT EDIT!


#ifndef OPTITRACK_ROS_MESSAGE_BODY_LIST_H
#define OPTITRACK_ROS_MESSAGE_BODY_LIST_H

#include <ros/service_traits.h>


#include <optitrack_ros/body_listRequest.h>
#include <optitrack_ros/body_listResponse.h>


namespace optitrack_ros
{

struct body_list
{

typedef body_listRequest Request;
typedef body_listResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct body_list
} // namespace optitrack_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::optitrack_ros::body_list > {
  static const char* value()
  {
    return "328d12a893d6c58c991b1ed688d06b9d";
  }

  static const char* value(const ::optitrack_ros::body_list&) { return value(); }
};

template<>
struct DataType< ::optitrack_ros::body_list > {
  static const char* value()
  {
    return "optitrack_ros/body_list";
  }

  static const char* value(const ::optitrack_ros::body_list&) { return value(); }
};


// service_traits::MD5Sum< ::optitrack_ros::body_listRequest> should match 
// service_traits::MD5Sum< ::optitrack_ros::body_list > 
template<>
struct MD5Sum< ::optitrack_ros::body_listRequest>
{
  static const char* value()
  {
    return MD5Sum< ::optitrack_ros::body_list >::value();
  }
  static const char* value(const ::optitrack_ros::body_listRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::optitrack_ros::body_listRequest> should match 
// service_traits::DataType< ::optitrack_ros::body_list > 
template<>
struct DataType< ::optitrack_ros::body_listRequest>
{
  static const char* value()
  {
    return DataType< ::optitrack_ros::body_list >::value();
  }
  static const char* value(const ::optitrack_ros::body_listRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::optitrack_ros::body_listResponse> should match 
// service_traits::MD5Sum< ::optitrack_ros::body_list > 
template<>
struct MD5Sum< ::optitrack_ros::body_listResponse>
{
  static const char* value()
  {
    return MD5Sum< ::optitrack_ros::body_list >::value();
  }
  static const char* value(const ::optitrack_ros::body_listResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::optitrack_ros::body_listResponse> should match 
// service_traits::DataType< ::optitrack_ros::body_list > 
template<>
struct DataType< ::optitrack_ros::body_listResponse>
{
  static const char* value()
  {
    return DataType< ::optitrack_ros::body_list >::value();
  }
  static const char* value(const ::optitrack_ros::body_listResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OPTITRACK_ROS_MESSAGE_BODY_LIST_H
