// Generated by gencpp from file optitrack_ros/body_listResponse.msg
// DO NOT EDIT!


#ifndef OPTITRACK_ROS_MESSAGE_BODY_LISTRESPONSE_H
#define OPTITRACK_ROS_MESSAGE_BODY_LISTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace optitrack_ros
{
template <class ContainerAllocator>
struct body_listResponse_
{
  typedef body_listResponse_<ContainerAllocator> Type;

  body_listResponse_()
    : genom_success(false)
    , genom_exdetail()
    , body_list()  {
    }
  body_listResponse_(const ContainerAllocator& _alloc)
    : genom_success(false)
    , genom_exdetail(_alloc)
    , body_list(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _genom_success_type;
  _genom_success_type genom_success;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _genom_exdetail_type;
  _genom_exdetail_type genom_exdetail;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _body_list_type;
  _body_list_type body_list;





  typedef boost::shared_ptr< ::optitrack_ros::body_listResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::optitrack_ros::body_listResponse_<ContainerAllocator> const> ConstPtr;

}; // struct body_listResponse_

typedef ::optitrack_ros::body_listResponse_<std::allocator<void> > body_listResponse;

typedef boost::shared_ptr< ::optitrack_ros::body_listResponse > body_listResponsePtr;
typedef boost::shared_ptr< ::optitrack_ros::body_listResponse const> body_listResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::optitrack_ros::body_listResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::optitrack_ros::body_listResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace optitrack_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'optitrack_ros': ['optitrack_ros/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::optitrack_ros::body_listResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::optitrack_ros::body_listResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::optitrack_ros::body_listResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::optitrack_ros::body_listResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::optitrack_ros::body_listResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::optitrack_ros::body_listResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::optitrack_ros::body_listResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "328d12a893d6c58c991b1ed688d06b9d";
  }

  static const char* value(const ::optitrack_ros::body_listResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x328d12a893d6c58cULL;
  static const uint64_t static_value2 = 0x991b1ed688d06b9dULL;
};

template<class ContainerAllocator>
struct DataType< ::optitrack_ros::body_listResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "optitrack_ros/body_listResponse";
  }

  static const char* value(const ::optitrack_ros::body_listResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::optitrack_ros::body_listResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool genom_success\n\
string genom_exdetail\n\
string[] body_list\n\
\n\
";
  }

  static const char* value(const ::optitrack_ros::body_listResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::optitrack_ros::body_listResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.genom_success);
      stream.next(m.genom_exdetail);
      stream.next(m.body_list);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct body_listResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::optitrack_ros::body_listResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::optitrack_ros::body_listResponse_<ContainerAllocator>& v)
  {
    s << indent << "genom_success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.genom_success);
    s << indent << "genom_exdetail: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.genom_exdetail);
    s << indent << "body_list[]" << std::endl;
    for (size_t i = 0; i < v.body_list.size(); ++i)
    {
      s << indent << "  body_list[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.body_list[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPTITRACK_ROS_MESSAGE_BODY_LISTRESPONSE_H
