// Generated by gencpp from file optitrack_ros/connect_port.msg
// DO NOT EDIT!


#ifndef OPTITRACK_ROS_MESSAGE_CONNECT_PORT_H
#define OPTITRACK_ROS_MESSAGE_CONNECT_PORT_H

#include <ros/service_traits.h>


#include <optitrack_ros/connect_portRequest.h>
#include <optitrack_ros/connect_portResponse.h>


namespace optitrack_ros
{

struct connect_port
{

typedef connect_portRequest Request;
typedef connect_portResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct connect_port
} // namespace optitrack_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::optitrack_ros::connect_port > {
  static const char* value()
  {
    return "f373a4b174400403f47052cfc240215e";
  }

  static const char* value(const ::optitrack_ros::connect_port&) { return value(); }
};

template<>
struct DataType< ::optitrack_ros::connect_port > {
  static const char* value()
  {
    return "optitrack_ros/connect_port";
  }

  static const char* value(const ::optitrack_ros::connect_port&) { return value(); }
};


// service_traits::MD5Sum< ::optitrack_ros::connect_portRequest> should match 
// service_traits::MD5Sum< ::optitrack_ros::connect_port > 
template<>
struct MD5Sum< ::optitrack_ros::connect_portRequest>
{
  static const char* value()
  {
    return MD5Sum< ::optitrack_ros::connect_port >::value();
  }
  static const char* value(const ::optitrack_ros::connect_portRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::optitrack_ros::connect_portRequest> should match 
// service_traits::DataType< ::optitrack_ros::connect_port > 
template<>
struct DataType< ::optitrack_ros::connect_portRequest>
{
  static const char* value()
  {
    return DataType< ::optitrack_ros::connect_port >::value();
  }
  static const char* value(const ::optitrack_ros::connect_portRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::optitrack_ros::connect_portResponse> should match 
// service_traits::MD5Sum< ::optitrack_ros::connect_port > 
template<>
struct MD5Sum< ::optitrack_ros::connect_portResponse>
{
  static const char* value()
  {
    return MD5Sum< ::optitrack_ros::connect_port >::value();
  }
  static const char* value(const ::optitrack_ros::connect_portResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::optitrack_ros::connect_portResponse> should match 
// service_traits::DataType< ::optitrack_ros::connect_port > 
template<>
struct DataType< ::optitrack_ros::connect_portResponse>
{
  static const char* value()
  {
    return DataType< ::optitrack_ros::connect_port >::value();
  }
  static const char* value(const ::optitrack_ros::connect_portResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OPTITRACK_ROS_MESSAGE_CONNECT_PORT_H
