// Generated by gencpp from file optitrack_ros/connect_service.msg
// DO NOT EDIT!


#ifndef OPTITRACK_ROS_MESSAGE_CONNECT_SERVICE_H
#define OPTITRACK_ROS_MESSAGE_CONNECT_SERVICE_H

#include <ros/service_traits.h>


#include <optitrack_ros/connect_serviceRequest.h>
#include <optitrack_ros/connect_serviceResponse.h>


namespace optitrack_ros
{

struct connect_service
{

typedef connect_serviceRequest Request;
typedef connect_serviceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct connect_service
} // namespace optitrack_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::optitrack_ros::connect_service > {
  static const char* value()
  {
    return "f373a4b174400403f47052cfc240215e";
  }

  static const char* value(const ::optitrack_ros::connect_service&) { return value(); }
};

template<>
struct DataType< ::optitrack_ros::connect_service > {
  static const char* value()
  {
    return "optitrack_ros/connect_service";
  }

  static const char* value(const ::optitrack_ros::connect_service&) { return value(); }
};


// service_traits::MD5Sum< ::optitrack_ros::connect_serviceRequest> should match 
// service_traits::MD5Sum< ::optitrack_ros::connect_service > 
template<>
struct MD5Sum< ::optitrack_ros::connect_serviceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::optitrack_ros::connect_service >::value();
  }
  static const char* value(const ::optitrack_ros::connect_serviceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::optitrack_ros::connect_serviceRequest> should match 
// service_traits::DataType< ::optitrack_ros::connect_service > 
template<>
struct DataType< ::optitrack_ros::connect_serviceRequest>
{
  static const char* value()
  {
    return DataType< ::optitrack_ros::connect_service >::value();
  }
  static const char* value(const ::optitrack_ros::connect_serviceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::optitrack_ros::connect_serviceResponse> should match 
// service_traits::MD5Sum< ::optitrack_ros::connect_service > 
template<>
struct MD5Sum< ::optitrack_ros::connect_serviceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::optitrack_ros::connect_service >::value();
  }
  static const char* value(const ::optitrack_ros::connect_serviceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::optitrack_ros::connect_serviceResponse> should match 
// service_traits::DataType< ::optitrack_ros::connect_service > 
template<>
struct DataType< ::optitrack_ros::connect_serviceResponse>
{
  static const char* value()
  {
    return DataType< ::optitrack_ros::connect_service >::value();
  }
  static const char* value(const ::optitrack_ros::connect_serviceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OPTITRACK_ROS_MESSAGE_CONNECT_SERVICE_H
