// Generated by gencpp from file optitrack_ros/genom_state_rusage.msg
// DO NOT EDIT!


#ifndef OPTITRACK_ROS_MESSAGE_GENOM_STATE_RUSAGE_H
#define OPTITRACK_ROS_MESSAGE_GENOM_STATE_RUSAGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <optitrack_ros/genom_state_stats.h>
#include <optitrack_ros/genom_state_stats.h>

namespace optitrack_ros
{
template <class ContainerAllocator>
struct genom_state_rusage_
{
  typedef genom_state_rusage_<ContainerAllocator> Type;

  genom_state_rusage_()
    : cycles(0)
    , timings()
    , load()  {
    }
  genom_state_rusage_(const ContainerAllocator& _alloc)
    : cycles(0)
    , timings(_alloc)
    , load(_alloc)  {
  (void)_alloc;
    }



   typedef uint32_t _cycles_type;
  _cycles_type cycles;

   typedef  ::optitrack_ros::genom_state_stats_<ContainerAllocator>  _timings_type;
  _timings_type timings;

   typedef  ::optitrack_ros::genom_state_stats_<ContainerAllocator>  _load_type;
  _load_type load;





  typedef boost::shared_ptr< ::optitrack_ros::genom_state_rusage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::optitrack_ros::genom_state_rusage_<ContainerAllocator> const> ConstPtr;

}; // struct genom_state_rusage_

typedef ::optitrack_ros::genom_state_rusage_<std::allocator<void> > genom_state_rusage;

typedef boost::shared_ptr< ::optitrack_ros::genom_state_rusage > genom_state_rusagePtr;
typedef boost::shared_ptr< ::optitrack_ros::genom_state_rusage const> genom_state_rusageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::optitrack_ros::genom_state_rusage_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::optitrack_ros::genom_state_rusage_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace optitrack_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/msg'], 'optitrack_ros': ['optitrack_ros/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::optitrack_ros::genom_state_rusage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::optitrack_ros::genom_state_rusage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::optitrack_ros::genom_state_rusage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::optitrack_ros::genom_state_rusage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::optitrack_ros::genom_state_rusage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::optitrack_ros::genom_state_rusage_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::optitrack_ros::genom_state_rusage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9320d7fd882241a75db2adb6f1c2cacb";
  }

  static const char* value(const ::optitrack_ros::genom_state_rusage_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9320d7fd882241a7ULL;
  static const uint64_t static_value2 = 0x5db2adb6f1c2cacbULL;
};

template<class ContainerAllocator>
struct DataType< ::optitrack_ros::genom_state_rusage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "optitrack_ros/genom_state_rusage";
  }

  static const char* value(const ::optitrack_ros::genom_state_rusage_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::optitrack_ros::genom_state_rusage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# IDL struct ::genom::state::rusage\n\
uint32 cycles\n\
genom_state_stats timings\n\
genom_state_stats load\n\
\n\
================================================================================\n\
MSG: optitrack_ros/genom_state_stats\n\
# IDL struct ::genom::state::stats\n\
float32 last\n\
float32 max\n\
float32 avg\n\
";
  }

  static const char* value(const ::optitrack_ros::genom_state_rusage_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::optitrack_ros::genom_state_rusage_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cycles);
      stream.next(m.timings);
      stream.next(m.load);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct genom_state_rusage_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::optitrack_ros::genom_state_rusage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::optitrack_ros::genom_state_rusage_<ContainerAllocator>& v)
  {
    s << indent << "cycles: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.cycles);
    s << indent << "timings: ";
    s << std::endl;
    Printer< ::optitrack_ros::genom_state_stats_<ContainerAllocator> >::stream(s, indent + "  ", v.timings);
    s << indent << "load: ";
    s << std::endl;
    Printer< ::optitrack_ros::genom_state_stats_<ContainerAllocator> >::stream(s, indent + "  ", v.load);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPTITRACK_ROS_MESSAGE_GENOM_STATE_RUSAGE_H
