// Generated by gencpp from file optitrack_ros/genom_state_activity.msg
// DO NOT EDIT!


#ifndef OPTITRACK_ROS_MESSAGE_GENOM_STATE_ACTIVITY_H
#define OPTITRACK_ROS_MESSAGE_GENOM_STATE_ACTIVITY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace optitrack_ros
{
template <class ContainerAllocator>
struct genom_state_activity_
{
  typedef genom_state_activity_<ContainerAllocator> Type;

  genom_state_activity_()
    : id(0)
    , name()  {
    }
  genom_state_activity_(const ContainerAllocator& _alloc)
    : id(0)
    , name(_alloc)  {
  (void)_alloc;
    }



   typedef uint32_t _id_type;
  _id_type id;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;





  typedef boost::shared_ptr< ::optitrack_ros::genom_state_activity_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::optitrack_ros::genom_state_activity_<ContainerAllocator> const> ConstPtr;

}; // struct genom_state_activity_

typedef ::optitrack_ros::genom_state_activity_<std::allocator<void> > genom_state_activity;

typedef boost::shared_ptr< ::optitrack_ros::genom_state_activity > genom_state_activityPtr;
typedef boost::shared_ptr< ::optitrack_ros::genom_state_activity const> genom_state_activityConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::optitrack_ros::genom_state_activity_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::optitrack_ros::genom_state_activity_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace optitrack_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/msg'], 'optitrack_ros': ['optitrack_ros/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::optitrack_ros::genom_state_activity_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::optitrack_ros::genom_state_activity_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::optitrack_ros::genom_state_activity_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::optitrack_ros::genom_state_activity_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::optitrack_ros::genom_state_activity_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::optitrack_ros::genom_state_activity_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::optitrack_ros::genom_state_activity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "09e1c3a5f79c5407a596e4c5d8e34a93";
  }

  static const char* value(const ::optitrack_ros::genom_state_activity_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x09e1c3a5f79c5407ULL;
  static const uint64_t static_value2 = 0xa596e4c5d8e34a93ULL;
};

template<class ContainerAllocator>
struct DataType< ::optitrack_ros::genom_state_activity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "optitrack_ros/genom_state_activity";
  }

  static const char* value(const ::optitrack_ros::genom_state_activity_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::optitrack_ros::genom_state_activity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# IDL struct ::genom::state::activity\n\
uint32 id\n\
string name\n\
";
  }

  static const char* value(const ::optitrack_ros::genom_state_activity_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::optitrack_ros::genom_state_activity_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct genom_state_activity_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::optitrack_ros::genom_state_activity_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::optitrack_ros::genom_state_activity_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.id);
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPTITRACK_ROS_MESSAGE_GENOM_STATE_ACTIVITY_H
