// Generated by gencpp from file optitrack_ros/get_logfile.msg
// DO NOT EDIT!


#ifndef OPTITRACK_ROS_MESSAGE_GET_LOGFILE_H
#define OPTITRACK_ROS_MESSAGE_GET_LOGFILE_H

#include <ros/service_traits.h>


#include <optitrack_ros/get_logfileRequest.h>
#include <optitrack_ros/get_logfileResponse.h>


namespace optitrack_ros
{

struct get_logfile
{

typedef get_logfileRequest Request;
typedef get_logfileResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct get_logfile
} // namespace optitrack_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::optitrack_ros::get_logfile > {
  static const char* value()
  {
    return "b87d842ccd0496b59e6eaee6d6cf4127";
  }

  static const char* value(const ::optitrack_ros::get_logfile&) { return value(); }
};

template<>
struct DataType< ::optitrack_ros::get_logfile > {
  static const char* value()
  {
    return "optitrack_ros/get_logfile";
  }

  static const char* value(const ::optitrack_ros::get_logfile&) { return value(); }
};


// service_traits::MD5Sum< ::optitrack_ros::get_logfileRequest> should match 
// service_traits::MD5Sum< ::optitrack_ros::get_logfile > 
template<>
struct MD5Sum< ::optitrack_ros::get_logfileRequest>
{
  static const char* value()
  {
    return MD5Sum< ::optitrack_ros::get_logfile >::value();
  }
  static const char* value(const ::optitrack_ros::get_logfileRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::optitrack_ros::get_logfileRequest> should match 
// service_traits::DataType< ::optitrack_ros::get_logfile > 
template<>
struct DataType< ::optitrack_ros::get_logfileRequest>
{
  static const char* value()
  {
    return DataType< ::optitrack_ros::get_logfile >::value();
  }
  static const char* value(const ::optitrack_ros::get_logfileRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::optitrack_ros::get_logfileResponse> should match 
// service_traits::MD5Sum< ::optitrack_ros::get_logfile > 
template<>
struct MD5Sum< ::optitrack_ros::get_logfileResponse>
{
  static const char* value()
  {
    return MD5Sum< ::optitrack_ros::get_logfile >::value();
  }
  static const char* value(const ::optitrack_ros::get_logfileResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::optitrack_ros::get_logfileResponse> should match 
// service_traits::DataType< ::optitrack_ros::get_logfile > 
template<>
struct DataType< ::optitrack_ros::get_logfileResponse>
{
  static const char* value()
  {
    return DataType< ::optitrack_ros::get_logfile >::value();
  }
  static const char* value(const ::optitrack_ros::get_logfileResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OPTITRACK_ROS_MESSAGE_GET_LOGFILE_H
