// Generated by gencpp from file optitrack_ros/get_noise.msg
// DO NOT EDIT!


#ifndef OPTITRACK_ROS_MESSAGE_GET_NOISE_H
#define OPTITRACK_ROS_MESSAGE_GET_NOISE_H

#include <ros/service_traits.h>


#include <optitrack_ros/get_noiseRequest.h>
#include <optitrack_ros/get_noiseResponse.h>


namespace optitrack_ros
{

struct get_noise
{

typedef get_noiseRequest Request;
typedef get_noiseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct get_noise
} // namespace optitrack_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::optitrack_ros::get_noise > {
  static const char* value()
  {
    return "a25689bbeace5841059475aaeec5e400";
  }

  static const char* value(const ::optitrack_ros::get_noise&) { return value(); }
};

template<>
struct DataType< ::optitrack_ros::get_noise > {
  static const char* value()
  {
    return "optitrack_ros/get_noise";
  }

  static const char* value(const ::optitrack_ros::get_noise&) { return value(); }
};


// service_traits::MD5Sum< ::optitrack_ros::get_noiseRequest> should match 
// service_traits::MD5Sum< ::optitrack_ros::get_noise > 
template<>
struct MD5Sum< ::optitrack_ros::get_noiseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::optitrack_ros::get_noise >::value();
  }
  static const char* value(const ::optitrack_ros::get_noiseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::optitrack_ros::get_noiseRequest> should match 
// service_traits::DataType< ::optitrack_ros::get_noise > 
template<>
struct DataType< ::optitrack_ros::get_noiseRequest>
{
  static const char* value()
  {
    return DataType< ::optitrack_ros::get_noise >::value();
  }
  static const char* value(const ::optitrack_ros::get_noiseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::optitrack_ros::get_noiseResponse> should match 
// service_traits::MD5Sum< ::optitrack_ros::get_noise > 
template<>
struct MD5Sum< ::optitrack_ros::get_noiseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::optitrack_ros::get_noise >::value();
  }
  static const char* value(const ::optitrack_ros::get_noiseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::optitrack_ros::get_noiseResponse> should match 
// service_traits::DataType< ::optitrack_ros::get_noise > 
template<>
struct DataType< ::optitrack_ros::get_noiseResponse>
{
  static const char* value()
  {
    return DataType< ::optitrack_ros::get_noise >::value();
  }
  static const char* value(const ::optitrack_ros::get_noiseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OPTITRACK_ROS_MESSAGE_GET_NOISE_H
