// Generated by gencpp from file optitrack_ros/get_local_port.msg
// DO NOT EDIT!


#ifndef OPTITRACK_ROS_MESSAGE_GET_LOCAL_PORT_H
#define OPTITRACK_ROS_MESSAGE_GET_LOCAL_PORT_H

#include <ros/service_traits.h>


#include <optitrack_ros/get_local_portRequest.h>
#include <optitrack_ros/get_local_portResponse.h>


namespace optitrack_ros
{

struct get_local_port
{

typedef get_local_portRequest Request;
typedef get_local_portResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct get_local_port
} // namespace optitrack_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::optitrack_ros::get_local_port > {
  static const char* value()
  {
    return "ab235123c219c0c5a555bd72f2eb478c";
  }

  static const char* value(const ::optitrack_ros::get_local_port&) { return value(); }
};

template<>
struct DataType< ::optitrack_ros::get_local_port > {
  static const char* value()
  {
    return "optitrack_ros/get_local_port";
  }

  static const char* value(const ::optitrack_ros::get_local_port&) { return value(); }
};


// service_traits::MD5Sum< ::optitrack_ros::get_local_portRequest> should match 
// service_traits::MD5Sum< ::optitrack_ros::get_local_port > 
template<>
struct MD5Sum< ::optitrack_ros::get_local_portRequest>
{
  static const char* value()
  {
    return MD5Sum< ::optitrack_ros::get_local_port >::value();
  }
  static const char* value(const ::optitrack_ros::get_local_portRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::optitrack_ros::get_local_portRequest> should match 
// service_traits::DataType< ::optitrack_ros::get_local_port > 
template<>
struct DataType< ::optitrack_ros::get_local_portRequest>
{
  static const char* value()
  {
    return DataType< ::optitrack_ros::get_local_port >::value();
  }
  static const char* value(const ::optitrack_ros::get_local_portRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::optitrack_ros::get_local_portResponse> should match 
// service_traits::MD5Sum< ::optitrack_ros::get_local_port > 
template<>
struct MD5Sum< ::optitrack_ros::get_local_portResponse>
{
  static const char* value()
  {
    return MD5Sum< ::optitrack_ros::get_local_port >::value();
  }
  static const char* value(const ::optitrack_ros::get_local_portResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::optitrack_ros::get_local_portResponse> should match 
// service_traits::DataType< ::optitrack_ros::get_local_port > 
template<>
struct DataType< ::optitrack_ros::get_local_portResponse>
{
  static const char* value()
  {
    return DataType< ::optitrack_ros::get_local_port >::value();
  }
  static const char* value(const ::optitrack_ros::get_local_portResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OPTITRACK_ROS_MESSAGE_GET_LOCAL_PORT_H
