// Generated by gencpp from file optitrack_ros/get_bw.msg
// DO NOT EDIT!


#ifndef OPTITRACK_ROS_MESSAGE_GET_BW_H
#define OPTITRACK_ROS_MESSAGE_GET_BW_H

#include <ros/service_traits.h>


#include <optitrack_ros/get_bwRequest.h>
#include <optitrack_ros/get_bwResponse.h>


namespace optitrack_ros
{

struct get_bw
{

typedef get_bwRequest Request;
typedef get_bwResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct get_bw
} // namespace optitrack_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::optitrack_ros::get_bw > {
  static const char* value()
  {
    return "a657b2c44ed438a458fda1debec3fff5";
  }

  static const char* value(const ::optitrack_ros::get_bw&) { return value(); }
};

template<>
struct DataType< ::optitrack_ros::get_bw > {
  static const char* value()
  {
    return "optitrack_ros/get_bw";
  }

  static const char* value(const ::optitrack_ros::get_bw&) { return value(); }
};


// service_traits::MD5Sum< ::optitrack_ros::get_bwRequest> should match 
// service_traits::MD5Sum< ::optitrack_ros::get_bw > 
template<>
struct MD5Sum< ::optitrack_ros::get_bwRequest>
{
  static const char* value()
  {
    return MD5Sum< ::optitrack_ros::get_bw >::value();
  }
  static const char* value(const ::optitrack_ros::get_bwRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::optitrack_ros::get_bwRequest> should match 
// service_traits::DataType< ::optitrack_ros::get_bw > 
template<>
struct DataType< ::optitrack_ros::get_bwRequest>
{
  static const char* value()
  {
    return DataType< ::optitrack_ros::get_bw >::value();
  }
  static const char* value(const ::optitrack_ros::get_bwRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::optitrack_ros::get_bwResponse> should match 
// service_traits::MD5Sum< ::optitrack_ros::get_bw > 
template<>
struct MD5Sum< ::optitrack_ros::get_bwResponse>
{
  static const char* value()
  {
    return MD5Sum< ::optitrack_ros::get_bw >::value();
  }
  static const char* value(const ::optitrack_ros::get_bwResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::optitrack_ros::get_bwResponse> should match 
// service_traits::DataType< ::optitrack_ros::get_bw > 
template<>
struct DataType< ::optitrack_ros::get_bwResponse>
{
  static const char* value()
  {
    return DataType< ::optitrack_ros::get_bw >::value();
  }
  static const char* value(const ::optitrack_ros::get_bwResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OPTITRACK_ROS_MESSAGE_GET_BW_H
