// Generated by gencpp from file optitrack_ros/kill.msg
// DO NOT EDIT!


#ifndef OPTITRACK_ROS_MESSAGE_KILL_H
#define OPTITRACK_ROS_MESSAGE_KILL_H

#include <ros/service_traits.h>


#include <optitrack_ros/killRequest.h>
#include <optitrack_ros/killResponse.h>


namespace optitrack_ros
{

struct kill
{

typedef killRequest Request;
typedef killResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct kill
} // namespace optitrack_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::optitrack_ros::kill > {
  static const char* value()
  {
    return "0d79450287345aef3f3e331856b25242";
  }

  static const char* value(const ::optitrack_ros::kill&) { return value(); }
};

template<>
struct DataType< ::optitrack_ros::kill > {
  static const char* value()
  {
    return "optitrack_ros/kill";
  }

  static const char* value(const ::optitrack_ros::kill&) { return value(); }
};


// service_traits::MD5Sum< ::optitrack_ros::killRequest> should match 
// service_traits::MD5Sum< ::optitrack_ros::kill > 
template<>
struct MD5Sum< ::optitrack_ros::killRequest>
{
  static const char* value()
  {
    return MD5Sum< ::optitrack_ros::kill >::value();
  }
  static const char* value(const ::optitrack_ros::killRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::optitrack_ros::killRequest> should match 
// service_traits::DataType< ::optitrack_ros::kill > 
template<>
struct DataType< ::optitrack_ros::killRequest>
{
  static const char* value()
  {
    return DataType< ::optitrack_ros::kill >::value();
  }
  static const char* value(const ::optitrack_ros::killRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::optitrack_ros::killResponse> should match 
// service_traits::MD5Sum< ::optitrack_ros::kill > 
template<>
struct MD5Sum< ::optitrack_ros::killResponse>
{
  static const char* value()
  {
    return MD5Sum< ::optitrack_ros::kill >::value();
  }
  static const char* value(const ::optitrack_ros::killResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::optitrack_ros::killResponse> should match 
// service_traits::DataType< ::optitrack_ros::kill > 
template<>
struct DataType< ::optitrack_ros::killResponse>
{
  static const char* value()
  {
    return DataType< ::optitrack_ros::kill >::value();
  }
  static const char* value(const ::optitrack_ros::killResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OPTITRACK_ROS_MESSAGE_KILL_H
