// Generated by gencpp from file optitrack_ros/optitrack_ids_pubdata_s.msg
// DO NOT EDIT!


#ifndef OPTITRACK_ROS_MESSAGE_OPTITRACK_IDS_PUBDATA_S_H
#define OPTITRACK_ROS_MESSAGE_OPTITRACK_IDS_PUBDATA_S_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace optitrack_ros
{
template <class ContainerAllocator>
struct optitrack_ids_pubdata_s_
{
  typedef optitrack_ids_pubdata_s_<ContainerAllocator> Type;

  optitrack_ids_pubdata_s_()
    : bodies(false)
    , markers(false)
    , anon(false)
    , gps_mode(false)
    , max_fps(0.0)  {
    }
  optitrack_ids_pubdata_s_(const ContainerAllocator& _alloc)
    : bodies(false)
    , markers(false)
    , anon(false)
    , gps_mode(false)
    , max_fps(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _bodies_type;
  _bodies_type bodies;

   typedef uint8_t _markers_type;
  _markers_type markers;

   typedef uint8_t _anon_type;
  _anon_type anon;

   typedef uint8_t _gps_mode_type;
  _gps_mode_type gps_mode;

   typedef double _max_fps_type;
  _max_fps_type max_fps;





  typedef boost::shared_ptr< ::optitrack_ros::optitrack_ids_pubdata_s_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::optitrack_ros::optitrack_ids_pubdata_s_<ContainerAllocator> const> ConstPtr;

}; // struct optitrack_ids_pubdata_s_

typedef ::optitrack_ros::optitrack_ids_pubdata_s_<std::allocator<void> > optitrack_ids_pubdata_s;

typedef boost::shared_ptr< ::optitrack_ros::optitrack_ids_pubdata_s > optitrack_ids_pubdata_sPtr;
typedef boost::shared_ptr< ::optitrack_ros::optitrack_ids_pubdata_s const> optitrack_ids_pubdata_sConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::optitrack_ros::optitrack_ids_pubdata_s_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::optitrack_ros::optitrack_ids_pubdata_s_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace optitrack_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/msg'], 'optitrack_ros': ['optitrack_ros/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::optitrack_ros::optitrack_ids_pubdata_s_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::optitrack_ros::optitrack_ids_pubdata_s_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::optitrack_ros::optitrack_ids_pubdata_s_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::optitrack_ros::optitrack_ids_pubdata_s_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::optitrack_ros::optitrack_ids_pubdata_s_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::optitrack_ros::optitrack_ids_pubdata_s_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::optitrack_ros::optitrack_ids_pubdata_s_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ee1ab0b3a25fabe40ecce39028cd56e5";
  }

  static const char* value(const ::optitrack_ros::optitrack_ids_pubdata_s_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xee1ab0b3a25fabe4ULL;
  static const uint64_t static_value2 = 0x0ecce39028cd56e5ULL;
};

template<class ContainerAllocator>
struct DataType< ::optitrack_ros::optitrack_ids_pubdata_s_<ContainerAllocator> >
{
  static const char* value()
  {
    return "optitrack_ros/optitrack_ids_pubdata_s";
  }

  static const char* value(const ::optitrack_ros::optitrack_ids_pubdata_s_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::optitrack_ros::optitrack_ids_pubdata_s_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# IDL struct ::optitrack::ids::pubdata_s\n\
bool bodies\n\
bool markers\n\
bool anon\n\
bool gps_mode\n\
float64 max_fps\n\
";
  }

  static const char* value(const ::optitrack_ros::optitrack_ids_pubdata_s_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::optitrack_ros::optitrack_ids_pubdata_s_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.bodies);
      stream.next(m.markers);
      stream.next(m.anon);
      stream.next(m.gps_mode);
      stream.next(m.max_fps);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct optitrack_ids_pubdata_s_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::optitrack_ros::optitrack_ids_pubdata_s_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::optitrack_ros::optitrack_ids_pubdata_s_<ContainerAllocator>& v)
  {
    s << indent << "bodies: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.bodies);
    s << indent << "markers: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.markers);
    s << indent << "anon: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.anon);
    s << indent << "gps_mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.gps_mode);
    s << indent << "max_fps: ";
    Printer<double>::stream(s, indent + "  ", v.max_fps);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPTITRACK_ROS_MESSAGE_OPTITRACK_IDS_PUBDATA_S_H
