// Generated by gencpp from file optitrack_ros/optitrack_ids_noise_s.msg
// DO NOT EDIT!


#ifndef OPTITRACK_ROS_MESSAGE_OPTITRACK_IDS_NOISE_S_H
#define OPTITRACK_ROS_MESSAGE_OPTITRACK_IDS_NOISE_S_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace optitrack_ros
{
template <class ContainerAllocator>
struct optitrack_ids_noise_s_
{
  typedef optitrack_ids_noise_s_<ContainerAllocator> Type;

  optitrack_ids_noise_s_()
    : pstddev(0.0)
    , qstddev(0.0)  {
    }
  optitrack_ids_noise_s_(const ContainerAllocator& _alloc)
    : pstddev(0.0)
    , qstddev(0.0)  {
  (void)_alloc;
    }



   typedef double _pstddev_type;
  _pstddev_type pstddev;

   typedef double _qstddev_type;
  _qstddev_type qstddev;





  typedef boost::shared_ptr< ::optitrack_ros::optitrack_ids_noise_s_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::optitrack_ros::optitrack_ids_noise_s_<ContainerAllocator> const> ConstPtr;

}; // struct optitrack_ids_noise_s_

typedef ::optitrack_ros::optitrack_ids_noise_s_<std::allocator<void> > optitrack_ids_noise_s;

typedef boost::shared_ptr< ::optitrack_ros::optitrack_ids_noise_s > optitrack_ids_noise_sPtr;
typedef boost::shared_ptr< ::optitrack_ros::optitrack_ids_noise_s const> optitrack_ids_noise_sConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::optitrack_ros::optitrack_ids_noise_s_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::optitrack_ros::optitrack_ids_noise_s_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace optitrack_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/msg'], 'optitrack_ros': ['optitrack_ros/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::optitrack_ros::optitrack_ids_noise_s_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::optitrack_ros::optitrack_ids_noise_s_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::optitrack_ros::optitrack_ids_noise_s_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::optitrack_ros::optitrack_ids_noise_s_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::optitrack_ros::optitrack_ids_noise_s_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::optitrack_ros::optitrack_ids_noise_s_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::optitrack_ros::optitrack_ids_noise_s_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d83b634a859dc2927ee57002479b238b";
  }

  static const char* value(const ::optitrack_ros::optitrack_ids_noise_s_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd83b634a859dc292ULL;
  static const uint64_t static_value2 = 0x7ee57002479b238bULL;
};

template<class ContainerAllocator>
struct DataType< ::optitrack_ros::optitrack_ids_noise_s_<ContainerAllocator> >
{
  static const char* value()
  {
    return "optitrack_ros/optitrack_ids_noise_s";
  }

  static const char* value(const ::optitrack_ros::optitrack_ids_noise_s_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::optitrack_ros::optitrack_ids_noise_s_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# IDL struct ::optitrack::ids::noise_s\n\
float64 pstddev\n\
float64 qstddev\n\
";
  }

  static const char* value(const ::optitrack_ros::optitrack_ids_noise_s_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::optitrack_ros::optitrack_ids_noise_s_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pstddev);
      stream.next(m.qstddev);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct optitrack_ids_noise_s_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::optitrack_ros::optitrack_ids_noise_s_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::optitrack_ros::optitrack_ids_noise_s_<ContainerAllocator>& v)
  {
    s << indent << "pstddev: ";
    Printer<double>::stream(s, indent + "  ", v.pstddev);
    s << indent << "qstddev: ";
    Printer<double>::stream(s, indent + "  ", v.qstddev);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPTITRACK_ROS_MESSAGE_OPTITRACK_IDS_NOISE_S_H
