// Generated by gencpp from file optitrack_ros/or_t3d_acc.msg
// DO NOT EDIT!


#ifndef OPTITRACK_ROS_MESSAGE_OR_T3D_ACC_H
#define OPTITRACK_ROS_MESSAGE_OR_T3D_ACC_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace optitrack_ros
{
template <class ContainerAllocator>
struct or_t3d_acc_
{
  typedef or_t3d_acc_<ContainerAllocator> Type;

  or_t3d_acc_()
    : ax(0.0)
    , ay(0.0)
    , az(0.0)  {
    }
  or_t3d_acc_(const ContainerAllocator& _alloc)
    : ax(0.0)
    , ay(0.0)
    , az(0.0)  {
  (void)_alloc;
    }



   typedef double _ax_type;
  _ax_type ax;

   typedef double _ay_type;
  _ay_type ay;

   typedef double _az_type;
  _az_type az;





  typedef boost::shared_ptr< ::optitrack_ros::or_t3d_acc_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::optitrack_ros::or_t3d_acc_<ContainerAllocator> const> ConstPtr;

}; // struct or_t3d_acc_

typedef ::optitrack_ros::or_t3d_acc_<std::allocator<void> > or_t3d_acc;

typedef boost::shared_ptr< ::optitrack_ros::or_t3d_acc > or_t3d_accPtr;
typedef boost::shared_ptr< ::optitrack_ros::or_t3d_acc const> or_t3d_accConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::optitrack_ros::or_t3d_acc_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::optitrack_ros::or_t3d_acc_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace optitrack_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/msg'], 'optitrack_ros': ['optitrack_ros/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::optitrack_ros::or_t3d_acc_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::optitrack_ros::or_t3d_acc_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::optitrack_ros::or_t3d_acc_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::optitrack_ros::or_t3d_acc_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::optitrack_ros::or_t3d_acc_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::optitrack_ros::or_t3d_acc_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::optitrack_ros::or_t3d_acc_<ContainerAllocator> >
{
  static const char* value()
  {
    return "271a8351f08a1993852d2e5e55f1efa1";
  }

  static const char* value(const ::optitrack_ros::or_t3d_acc_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x271a8351f08a1993ULL;
  static const uint64_t static_value2 = 0x852d2e5e55f1efa1ULL;
};

template<class ContainerAllocator>
struct DataType< ::optitrack_ros::or_t3d_acc_<ContainerAllocator> >
{
  static const char* value()
  {
    return "optitrack_ros/or_t3d_acc";
  }

  static const char* value(const ::optitrack_ros::or_t3d_acc_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::optitrack_ros::or_t3d_acc_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# IDL struct ::or::t3d::acc\n\
float64 ax\n\
float64 ay\n\
float64 az\n\
";
  }

  static const char* value(const ::optitrack_ros::or_t3d_acc_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::optitrack_ros::or_t3d_acc_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ax);
      stream.next(m.ay);
      stream.next(m.az);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct or_t3d_acc_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::optitrack_ros::or_t3d_acc_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::optitrack_ros::or_t3d_acc_<ContainerAllocator>& v)
  {
    s << indent << "ax: ";
    Printer<double>::stream(s, indent + "  ", v.ax);
    s << indent << "ay: ";
    Printer<double>::stream(s, indent + "  ", v.ay);
    s << indent << "az: ";
    Printer<double>::stream(s, indent + "  ", v.az);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPTITRACK_ROS_MESSAGE_OR_T3D_ACC_H
