// Generated by gencpp from file optitrack_ros/or_time_ts.msg
// DO NOT EDIT!


#ifndef OPTITRACK_ROS_MESSAGE_OR_TIME_TS_H
#define OPTITRACK_ROS_MESSAGE_OR_TIME_TS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace optitrack_ros
{
template <class ContainerAllocator>
struct or_time_ts_
{
  typedef or_time_ts_<ContainerAllocator> Type;

  or_time_ts_()
    : sec(0)
    , nsec(0)  {
    }
  or_time_ts_(const ContainerAllocator& _alloc)
    : sec(0)
    , nsec(0)  {
  (void)_alloc;
    }



   typedef int32_t _sec_type;
  _sec_type sec;

   typedef int32_t _nsec_type;
  _nsec_type nsec;





  typedef boost::shared_ptr< ::optitrack_ros::or_time_ts_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::optitrack_ros::or_time_ts_<ContainerAllocator> const> ConstPtr;

}; // struct or_time_ts_

typedef ::optitrack_ros::or_time_ts_<std::allocator<void> > or_time_ts;

typedef boost::shared_ptr< ::optitrack_ros::or_time_ts > or_time_tsPtr;
typedef boost::shared_ptr< ::optitrack_ros::or_time_ts const> or_time_tsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::optitrack_ros::or_time_ts_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::optitrack_ros::or_time_ts_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace optitrack_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/msg'], 'optitrack_ros': ['optitrack_ros/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::optitrack_ros::or_time_ts_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::optitrack_ros::or_time_ts_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::optitrack_ros::or_time_ts_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::optitrack_ros::or_time_ts_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::optitrack_ros::or_time_ts_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::optitrack_ros::or_time_ts_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::optitrack_ros::or_time_ts_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bfddb48875549f618d724dc3ff7ed299";
  }

  static const char* value(const ::optitrack_ros::or_time_ts_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbfddb48875549f61ULL;
  static const uint64_t static_value2 = 0x8d724dc3ff7ed299ULL;
};

template<class ContainerAllocator>
struct DataType< ::optitrack_ros::or_time_ts_<ContainerAllocator> >
{
  static const char* value()
  {
    return "optitrack_ros/or_time_ts";
  }

  static const char* value(const ::optitrack_ros::or_time_ts_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::optitrack_ros::or_time_ts_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# IDL struct ::or::time::ts\n\
int32 sec\n\
int32 nsec\n\
";
  }

  static const char* value(const ::optitrack_ros::or_time_ts_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::optitrack_ros::or_time_ts_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sec);
      stream.next(m.nsec);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct or_time_ts_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::optitrack_ros::or_time_ts_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::optitrack_ros::or_time_ts_<ContainerAllocator>& v)
  {
    s << indent << "sec: ";
    Printer<int32_t>::stream(s, indent + "  ", v.sec);
    s << indent << "nsec: ";
    Printer<int32_t>::stream(s, indent + "  ", v.nsec);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPTITRACK_ROS_MESSAGE_OR_TIME_TS_H
