// Generated by gencpp from file optitrack_ros/or_t3d_att.msg
// DO NOT EDIT!


#ifndef OPTITRACK_ROS_MESSAGE_OR_T3D_ATT_H
#define OPTITRACK_ROS_MESSAGE_OR_T3D_ATT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace optitrack_ros
{
template <class ContainerAllocator>
struct or_t3d_att_
{
  typedef or_t3d_att_<ContainerAllocator> Type;

  or_t3d_att_()
    : qw(0.0)
    , qx(0.0)
    , qy(0.0)
    , qz(0.0)  {
    }
  or_t3d_att_(const ContainerAllocator& _alloc)
    : qw(0.0)
    , qx(0.0)
    , qy(0.0)
    , qz(0.0)  {
  (void)_alloc;
    }



   typedef double _qw_type;
  _qw_type qw;

   typedef double _qx_type;
  _qx_type qx;

   typedef double _qy_type;
  _qy_type qy;

   typedef double _qz_type;
  _qz_type qz;





  typedef boost::shared_ptr< ::optitrack_ros::or_t3d_att_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::optitrack_ros::or_t3d_att_<ContainerAllocator> const> ConstPtr;

}; // struct or_t3d_att_

typedef ::optitrack_ros::or_t3d_att_<std::allocator<void> > or_t3d_att;

typedef boost::shared_ptr< ::optitrack_ros::or_t3d_att > or_t3d_attPtr;
typedef boost::shared_ptr< ::optitrack_ros::or_t3d_att const> or_t3d_attConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::optitrack_ros::or_t3d_att_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::optitrack_ros::or_t3d_att_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace optitrack_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/msg'], 'optitrack_ros': ['optitrack_ros/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::optitrack_ros::or_t3d_att_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::optitrack_ros::or_t3d_att_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::optitrack_ros::or_t3d_att_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::optitrack_ros::or_t3d_att_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::optitrack_ros::or_t3d_att_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::optitrack_ros::or_t3d_att_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::optitrack_ros::or_t3d_att_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2fcc91b88683e83e65b02ee86cd6f36a";
  }

  static const char* value(const ::optitrack_ros::or_t3d_att_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2fcc91b88683e83eULL;
  static const uint64_t static_value2 = 0x65b02ee86cd6f36aULL;
};

template<class ContainerAllocator>
struct DataType< ::optitrack_ros::or_t3d_att_<ContainerAllocator> >
{
  static const char* value()
  {
    return "optitrack_ros/or_t3d_att";
  }

  static const char* value(const ::optitrack_ros::or_t3d_att_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::optitrack_ros::or_t3d_att_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# IDL struct ::or::t3d::att\n\
float64 qw\n\
float64 qx\n\
float64 qy\n\
float64 qz\n\
";
  }

  static const char* value(const ::optitrack_ros::or_t3d_att_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::optitrack_ros::or_t3d_att_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.qw);
      stream.next(m.qx);
      stream.next(m.qy);
      stream.next(m.qz);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct or_t3d_att_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::optitrack_ros::or_t3d_att_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::optitrack_ros::or_t3d_att_<ContainerAllocator>& v)
  {
    s << indent << "qw: ";
    Printer<double>::stream(s, indent + "  ", v.qw);
    s << indent << "qx: ";
    Printer<double>::stream(s, indent + "  ", v.qx);
    s << indent << "qy: ";
    Printer<double>::stream(s, indent + "  ", v.qy);
    s << indent << "qz: ";
    Printer<double>::stream(s, indent + "  ", v.qz);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPTITRACK_ROS_MESSAGE_OR_T3D_ATT_H
