// Generated by gencpp from file optitrack_ros/or_t3d_att_cov.msg
// DO NOT EDIT!


#ifndef OPTITRACK_ROS_MESSAGE_OR_T3D_ATT_COV_H
#define OPTITRACK_ROS_MESSAGE_OR_T3D_ATT_COV_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace optitrack_ros
{
template <class ContainerAllocator>
struct or_t3d_att_cov_
{
  typedef or_t3d_att_cov_<ContainerAllocator> Type;

  or_t3d_att_cov_()
    : cov()  {
      cov.assign(0.0);
  }
  or_t3d_att_cov_(const ContainerAllocator& _alloc)
    : cov()  {
  (void)_alloc;
      cov.assign(0.0);
  }



   typedef boost::array<double, 10>  _cov_type;
  _cov_type cov;





  typedef boost::shared_ptr< ::optitrack_ros::or_t3d_att_cov_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::optitrack_ros::or_t3d_att_cov_<ContainerAllocator> const> ConstPtr;

}; // struct or_t3d_att_cov_

typedef ::optitrack_ros::or_t3d_att_cov_<std::allocator<void> > or_t3d_att_cov;

typedef boost::shared_ptr< ::optitrack_ros::or_t3d_att_cov > or_t3d_att_covPtr;
typedef boost::shared_ptr< ::optitrack_ros::or_t3d_att_cov const> or_t3d_att_covConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::optitrack_ros::or_t3d_att_cov_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::optitrack_ros::or_t3d_att_cov_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace optitrack_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/msg'], 'optitrack_ros': ['optitrack_ros/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::optitrack_ros::or_t3d_att_cov_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::optitrack_ros::or_t3d_att_cov_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::optitrack_ros::or_t3d_att_cov_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::optitrack_ros::or_t3d_att_cov_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::optitrack_ros::or_t3d_att_cov_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::optitrack_ros::or_t3d_att_cov_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::optitrack_ros::or_t3d_att_cov_<ContainerAllocator> >
{
  static const char* value()
  {
    return "748f45dca12ac5dd52695b975ecd5744";
  }

  static const char* value(const ::optitrack_ros::or_t3d_att_cov_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x748f45dca12ac5ddULL;
  static const uint64_t static_value2 = 0x52695b975ecd5744ULL;
};

template<class ContainerAllocator>
struct DataType< ::optitrack_ros::or_t3d_att_cov_<ContainerAllocator> >
{
  static const char* value()
  {
    return "optitrack_ros/or_t3d_att_cov";
  }

  static const char* value(const ::optitrack_ros::or_t3d_att_cov_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::optitrack_ros::or_t3d_att_cov_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# IDL struct ::or::t3d::att_cov\n\
float64[10] cov\n\
";
  }

  static const char* value(const ::optitrack_ros::or_t3d_att_cov_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::optitrack_ros::or_t3d_att_cov_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cov);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct or_t3d_att_cov_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::optitrack_ros::or_t3d_att_cov_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::optitrack_ros::or_t3d_att_cov_<ContainerAllocator>& v)
  {
    s << indent << "cov[]" << std::endl;
    for (size_t i = 0; i < v.cov.size(); ++i)
    {
      s << indent << "  cov[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.cov[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPTITRACK_ROS_MESSAGE_OR_T3D_ATT_COV_H
