// Generated by gencpp from file optitrack_ros/or_t3d_aacc.msg
// DO NOT EDIT!


#ifndef OPTITRACK_ROS_MESSAGE_OR_T3D_AACC_H
#define OPTITRACK_ROS_MESSAGE_OR_T3D_AACC_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace optitrack_ros
{
template <class ContainerAllocator>
struct or_t3d_aacc_
{
  typedef or_t3d_aacc_<ContainerAllocator> Type;

  or_t3d_aacc_()
    : awx(0.0)
    , awy(0.0)
    , awz(0.0)  {
    }
  or_t3d_aacc_(const ContainerAllocator& _alloc)
    : awx(0.0)
    , awy(0.0)
    , awz(0.0)  {
  (void)_alloc;
    }



   typedef double _awx_type;
  _awx_type awx;

   typedef double _awy_type;
  _awy_type awy;

   typedef double _awz_type;
  _awz_type awz;





  typedef boost::shared_ptr< ::optitrack_ros::or_t3d_aacc_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::optitrack_ros::or_t3d_aacc_<ContainerAllocator> const> ConstPtr;

}; // struct or_t3d_aacc_

typedef ::optitrack_ros::or_t3d_aacc_<std::allocator<void> > or_t3d_aacc;

typedef boost::shared_ptr< ::optitrack_ros::or_t3d_aacc > or_t3d_aaccPtr;
typedef boost::shared_ptr< ::optitrack_ros::or_t3d_aacc const> or_t3d_aaccConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::optitrack_ros::or_t3d_aacc_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::optitrack_ros::or_t3d_aacc_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace optitrack_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/msg'], 'optitrack_ros': ['optitrack_ros/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::optitrack_ros::or_t3d_aacc_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::optitrack_ros::or_t3d_aacc_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::optitrack_ros::or_t3d_aacc_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::optitrack_ros::or_t3d_aacc_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::optitrack_ros::or_t3d_aacc_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::optitrack_ros::or_t3d_aacc_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::optitrack_ros::or_t3d_aacc_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b13ad4e0626d0bd34a7ae51add9c5963";
  }

  static const char* value(const ::optitrack_ros::or_t3d_aacc_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb13ad4e0626d0bd3ULL;
  static const uint64_t static_value2 = 0x4a7ae51add9c5963ULL;
};

template<class ContainerAllocator>
struct DataType< ::optitrack_ros::or_t3d_aacc_<ContainerAllocator> >
{
  static const char* value()
  {
    return "optitrack_ros/or_t3d_aacc";
  }

  static const char* value(const ::optitrack_ros::or_t3d_aacc_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::optitrack_ros::or_t3d_aacc_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# IDL struct ::or::t3d::aacc\n\
float64 awx\n\
float64 awy\n\
float64 awz\n\
";
  }

  static const char* value(const ::optitrack_ros::or_t3d_aacc_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::optitrack_ros::or_t3d_aacc_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.awx);
      stream.next(m.awy);
      stream.next(m.awz);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct or_t3d_aacc_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::optitrack_ros::or_t3d_aacc_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::optitrack_ros::or_t3d_aacc_<ContainerAllocator>& v)
  {
    s << indent << "awx: ";
    Printer<double>::stream(s, indent + "  ", v.awx);
    s << indent << "awy: ";
    Printer<double>::stream(s, indent + "  ", v.awy);
    s << indent << "awz: ";
    Printer<double>::stream(s, indent + "  ", v.awz);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPTITRACK_ROS_MESSAGE_OR_T3D_AACC_H
