// Generated by gencpp from file optitrack_ros/refresh.msg
// DO NOT EDIT!


#ifndef OPTITRACK_ROS_MESSAGE_REFRESH_H
#define OPTITRACK_ROS_MESSAGE_REFRESH_H

#include <ros/service_traits.h>


#include <optitrack_ros/refreshRequest.h>
#include <optitrack_ros/refreshResponse.h>


namespace optitrack_ros
{

struct refresh
{

typedef refreshRequest Request;
typedef refreshResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct refresh
} // namespace optitrack_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::optitrack_ros::refresh > {
  static const char* value()
  {
    return "0d79450287345aef3f3e331856b25242";
  }

  static const char* value(const ::optitrack_ros::refresh&) { return value(); }
};

template<>
struct DataType< ::optitrack_ros::refresh > {
  static const char* value()
  {
    return "optitrack_ros/refresh";
  }

  static const char* value(const ::optitrack_ros::refresh&) { return value(); }
};


// service_traits::MD5Sum< ::optitrack_ros::refreshRequest> should match 
// service_traits::MD5Sum< ::optitrack_ros::refresh > 
template<>
struct MD5Sum< ::optitrack_ros::refreshRequest>
{
  static const char* value()
  {
    return MD5Sum< ::optitrack_ros::refresh >::value();
  }
  static const char* value(const ::optitrack_ros::refreshRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::optitrack_ros::refreshRequest> should match 
// service_traits::DataType< ::optitrack_ros::refresh > 
template<>
struct DataType< ::optitrack_ros::refreshRequest>
{
  static const char* value()
  {
    return DataType< ::optitrack_ros::refresh >::value();
  }
  static const char* value(const ::optitrack_ros::refreshRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::optitrack_ros::refreshResponse> should match 
// service_traits::MD5Sum< ::optitrack_ros::refresh > 
template<>
struct MD5Sum< ::optitrack_ros::refreshResponse>
{
  static const char* value()
  {
    return MD5Sum< ::optitrack_ros::refresh >::value();
  }
  static const char* value(const ::optitrack_ros::refreshResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::optitrack_ros::refreshResponse> should match 
// service_traits::DataType< ::optitrack_ros::refresh > 
template<>
struct DataType< ::optitrack_ros::refreshResponse>
{
  static const char* value()
  {
    return DataType< ::optitrack_ros::refresh >::value();
  }
  static const char* value(const ::optitrack_ros::refreshResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OPTITRACK_ROS_MESSAGE_REFRESH_H
