// Generated by gencpp from file optitrack_ros/set_gps_modeRequest.msg
// DO NOT EDIT!


#ifndef OPTITRACK_ROS_MESSAGE_SET_GPS_MODEREQUEST_H
#define OPTITRACK_ROS_MESSAGE_SET_GPS_MODEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace optitrack_ros
{
template <class ContainerAllocator>
struct set_gps_modeRequest_
{
  typedef set_gps_modeRequest_<ContainerAllocator> Type;

  set_gps_modeRequest_()
    : gps_mode(false)  {
    }
  set_gps_modeRequest_(const ContainerAllocator& _alloc)
    : gps_mode(false)  {
  (void)_alloc;
    }



   typedef uint8_t _gps_mode_type;
  _gps_mode_type gps_mode;





  typedef boost::shared_ptr< ::optitrack_ros::set_gps_modeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::optitrack_ros::set_gps_modeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct set_gps_modeRequest_

typedef ::optitrack_ros::set_gps_modeRequest_<std::allocator<void> > set_gps_modeRequest;

typedef boost::shared_ptr< ::optitrack_ros::set_gps_modeRequest > set_gps_modeRequestPtr;
typedef boost::shared_ptr< ::optitrack_ros::set_gps_modeRequest const> set_gps_modeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::optitrack_ros::set_gps_modeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::optitrack_ros::set_gps_modeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace optitrack_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'optitrack_ros': ['optitrack_ros/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::optitrack_ros::set_gps_modeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::optitrack_ros::set_gps_modeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::optitrack_ros::set_gps_modeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::optitrack_ros::set_gps_modeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::optitrack_ros::set_gps_modeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::optitrack_ros::set_gps_modeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::optitrack_ros::set_gps_modeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0def7eb360bf024b1a742dfca0d72ea9";
  }

  static const char* value(const ::optitrack_ros::set_gps_modeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0def7eb360bf024bULL;
  static const uint64_t static_value2 = 0x1a742dfca0d72ea9ULL;
};

template<class ContainerAllocator>
struct DataType< ::optitrack_ros::set_gps_modeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "optitrack_ros/set_gps_modeRequest";
  }

  static const char* value(const ::optitrack_ros::set_gps_modeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::optitrack_ros::set_gps_modeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
bool gps_mode\n\
";
  }

  static const char* value(const ::optitrack_ros::set_gps_modeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::optitrack_ros::set_gps_modeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.gps_mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct set_gps_modeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::optitrack_ros::set_gps_modeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::optitrack_ros::set_gps_modeRequest_<ContainerAllocator>& v)
  {
    s << indent << "gps_mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.gps_mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPTITRACK_ROS_MESSAGE_SET_GPS_MODEREQUEST_H
