// Generated by gencpp from file optitrack_ros/set_gps_mode.msg
// DO NOT EDIT!


#ifndef OPTITRACK_ROS_MESSAGE_SET_GPS_MODE_H
#define OPTITRACK_ROS_MESSAGE_SET_GPS_MODE_H

#include <ros/service_traits.h>


#include <optitrack_ros/set_gps_modeRequest.h>
#include <optitrack_ros/set_gps_modeResponse.h>


namespace optitrack_ros
{

struct set_gps_mode
{

typedef set_gps_modeRequest Request;
typedef set_gps_modeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct set_gps_mode
} // namespace optitrack_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::optitrack_ros::set_gps_mode > {
  static const char* value()
  {
    return "8a8a7e7d0683622896cb2751ceedc005";
  }

  static const char* value(const ::optitrack_ros::set_gps_mode&) { return value(); }
};

template<>
struct DataType< ::optitrack_ros::set_gps_mode > {
  static const char* value()
  {
    return "optitrack_ros/set_gps_mode";
  }

  static const char* value(const ::optitrack_ros::set_gps_mode&) { return value(); }
};


// service_traits::MD5Sum< ::optitrack_ros::set_gps_modeRequest> should match 
// service_traits::MD5Sum< ::optitrack_ros::set_gps_mode > 
template<>
struct MD5Sum< ::optitrack_ros::set_gps_modeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::optitrack_ros::set_gps_mode >::value();
  }
  static const char* value(const ::optitrack_ros::set_gps_modeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::optitrack_ros::set_gps_modeRequest> should match 
// service_traits::DataType< ::optitrack_ros::set_gps_mode > 
template<>
struct DataType< ::optitrack_ros::set_gps_modeRequest>
{
  static const char* value()
  {
    return DataType< ::optitrack_ros::set_gps_mode >::value();
  }
  static const char* value(const ::optitrack_ros::set_gps_modeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::optitrack_ros::set_gps_modeResponse> should match 
// service_traits::MD5Sum< ::optitrack_ros::set_gps_mode > 
template<>
struct MD5Sum< ::optitrack_ros::set_gps_modeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::optitrack_ros::set_gps_mode >::value();
  }
  static const char* value(const ::optitrack_ros::set_gps_modeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::optitrack_ros::set_gps_modeResponse> should match 
// service_traits::DataType< ::optitrack_ros::set_gps_mode > 
template<>
struct DataType< ::optitrack_ros::set_gps_modeResponse>
{
  static const char* value()
  {
    return DataType< ::optitrack_ros::set_gps_mode >::value();
  }
  static const char* value(const ::optitrack_ros::set_gps_modeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OPTITRACK_ROS_MESSAGE_SET_GPS_MODE_H
