// Generated by gencpp from file optitrack_ros/set_export.msg
// DO NOT EDIT!


#ifndef OPTITRACK_ROS_MESSAGE_SET_EXPORT_H
#define OPTITRACK_ROS_MESSAGE_SET_EXPORT_H

#include <ros/service_traits.h>


#include <optitrack_ros/set_exportRequest.h>
#include <optitrack_ros/set_exportResponse.h>


namespace optitrack_ros
{

struct set_export
{

typedef set_exportRequest Request;
typedef set_exportResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct set_export
} // namespace optitrack_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::optitrack_ros::set_export > {
  static const char* value()
  {
    return "f59f0232f7801f076c45240a4ade7e21";
  }

  static const char* value(const ::optitrack_ros::set_export&) { return value(); }
};

template<>
struct DataType< ::optitrack_ros::set_export > {
  static const char* value()
  {
    return "optitrack_ros/set_export";
  }

  static const char* value(const ::optitrack_ros::set_export&) { return value(); }
};


// service_traits::MD5Sum< ::optitrack_ros::set_exportRequest> should match 
// service_traits::MD5Sum< ::optitrack_ros::set_export > 
template<>
struct MD5Sum< ::optitrack_ros::set_exportRequest>
{
  static const char* value()
  {
    return MD5Sum< ::optitrack_ros::set_export >::value();
  }
  static const char* value(const ::optitrack_ros::set_exportRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::optitrack_ros::set_exportRequest> should match 
// service_traits::DataType< ::optitrack_ros::set_export > 
template<>
struct DataType< ::optitrack_ros::set_exportRequest>
{
  static const char* value()
  {
    return DataType< ::optitrack_ros::set_export >::value();
  }
  static const char* value(const ::optitrack_ros::set_exportRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::optitrack_ros::set_exportResponse> should match 
// service_traits::MD5Sum< ::optitrack_ros::set_export > 
template<>
struct MD5Sum< ::optitrack_ros::set_exportResponse>
{
  static const char* value()
  {
    return MD5Sum< ::optitrack_ros::set_export >::value();
  }
  static const char* value(const ::optitrack_ros::set_exportResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::optitrack_ros::set_exportResponse> should match 
// service_traits::DataType< ::optitrack_ros::set_export > 
template<>
struct DataType< ::optitrack_ros::set_exportResponse>
{
  static const char* value()
  {
    return DataType< ::optitrack_ros::set_export >::value();
  }
  static const char* value(const ::optitrack_ros::set_exportResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OPTITRACK_ROS_MESSAGE_SET_EXPORT_H
