// Generated by gencpp from file optitrack_ros/set_max_fpsRequest.msg
// DO NOT EDIT!


#ifndef OPTITRACK_ROS_MESSAGE_SET_MAX_FPSREQUEST_H
#define OPTITRACK_ROS_MESSAGE_SET_MAX_FPSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace optitrack_ros
{
template <class ContainerAllocator>
struct set_max_fpsRequest_
{
  typedef set_max_fpsRequest_<ContainerAllocator> Type;

  set_max_fpsRequest_()
    : max_fps(0.0)  {
    }
  set_max_fpsRequest_(const ContainerAllocator& _alloc)
    : max_fps(0.0)  {
  (void)_alloc;
    }



   typedef double _max_fps_type;
  _max_fps_type max_fps;





  typedef boost::shared_ptr< ::optitrack_ros::set_max_fpsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::optitrack_ros::set_max_fpsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct set_max_fpsRequest_

typedef ::optitrack_ros::set_max_fpsRequest_<std::allocator<void> > set_max_fpsRequest;

typedef boost::shared_ptr< ::optitrack_ros::set_max_fpsRequest > set_max_fpsRequestPtr;
typedef boost::shared_ptr< ::optitrack_ros::set_max_fpsRequest const> set_max_fpsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::optitrack_ros::set_max_fpsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::optitrack_ros::set_max_fpsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace optitrack_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'optitrack_ros': ['optitrack_ros/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::optitrack_ros::set_max_fpsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::optitrack_ros::set_max_fpsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::optitrack_ros::set_max_fpsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::optitrack_ros::set_max_fpsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::optitrack_ros::set_max_fpsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::optitrack_ros::set_max_fpsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::optitrack_ros::set_max_fpsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e18bdfb081c575c7444c2ab32bf401c5";
  }

  static const char* value(const ::optitrack_ros::set_max_fpsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe18bdfb081c575c7ULL;
  static const uint64_t static_value2 = 0x444c2ab32bf401c5ULL;
};

template<class ContainerAllocator>
struct DataType< ::optitrack_ros::set_max_fpsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "optitrack_ros/set_max_fpsRequest";
  }

  static const char* value(const ::optitrack_ros::set_max_fpsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::optitrack_ros::set_max_fpsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
float64 max_fps\n\
";
  }

  static const char* value(const ::optitrack_ros::set_max_fpsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::optitrack_ros::set_max_fpsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.max_fps);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct set_max_fpsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::optitrack_ros::set_max_fpsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::optitrack_ros::set_max_fpsRequest_<ContainerAllocator>& v)
  {
    s << indent << "max_fps: ";
    Printer<double>::stream(s, indent + "  ", v.max_fps);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPTITRACK_ROS_MESSAGE_SET_MAX_FPSREQUEST_H
