// Generated by gencpp from file optitrack_ros/set_local_portRequest.msg
// DO NOT EDIT!


#ifndef OPTITRACK_ROS_MESSAGE_SET_LOCAL_PORTREQUEST_H
#define OPTITRACK_ROS_MESSAGE_SET_LOCAL_PORTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace optitrack_ros
{
template <class ContainerAllocator>
struct set_local_portRequest_
{
  typedef set_local_portRequest_<ContainerAllocator> Type;

  set_local_portRequest_()
    : local_port(0)  {
    }
  set_local_portRequest_(const ContainerAllocator& _alloc)
    : local_port(0)  {
  (void)_alloc;
    }



   typedef uint16_t _local_port_type;
  _local_port_type local_port;





  typedef boost::shared_ptr< ::optitrack_ros::set_local_portRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::optitrack_ros::set_local_portRequest_<ContainerAllocator> const> ConstPtr;

}; // struct set_local_portRequest_

typedef ::optitrack_ros::set_local_portRequest_<std::allocator<void> > set_local_portRequest;

typedef boost::shared_ptr< ::optitrack_ros::set_local_portRequest > set_local_portRequestPtr;
typedef boost::shared_ptr< ::optitrack_ros::set_local_portRequest const> set_local_portRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::optitrack_ros::set_local_portRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::optitrack_ros::set_local_portRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace optitrack_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'optitrack_ros': ['optitrack_ros/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::optitrack_ros::set_local_portRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::optitrack_ros::set_local_portRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::optitrack_ros::set_local_portRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::optitrack_ros::set_local_portRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::optitrack_ros::set_local_portRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::optitrack_ros::set_local_portRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::optitrack_ros::set_local_portRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "66cf35452a2d56efdff79384a9602883";
  }

  static const char* value(const ::optitrack_ros::set_local_portRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x66cf35452a2d56efULL;
  static const uint64_t static_value2 = 0xdff79384a9602883ULL;
};

template<class ContainerAllocator>
struct DataType< ::optitrack_ros::set_local_portRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "optitrack_ros/set_local_portRequest";
  }

  static const char* value(const ::optitrack_ros::set_local_portRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::optitrack_ros::set_local_portRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
uint16 local_port\n\
";
  }

  static const char* value(const ::optitrack_ros::set_local_portRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::optitrack_ros::set_local_portRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.local_port);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct set_local_portRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::optitrack_ros::set_local_portRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::optitrack_ros::set_local_portRequest_<ContainerAllocator>& v)
  {
    s << indent << "local_port: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.local_port);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPTITRACK_ROS_MESSAGE_SET_LOCAL_PORTREQUEST_H
