// Generated by gencpp from file optitrack_ros/set_max_fps.msg
// DO NOT EDIT!


#ifndef OPTITRACK_ROS_MESSAGE_SET_MAX_FPS_H
#define OPTITRACK_ROS_MESSAGE_SET_MAX_FPS_H

#include <ros/service_traits.h>


#include <optitrack_ros/set_max_fpsRequest.h>
#include <optitrack_ros/set_max_fpsResponse.h>


namespace optitrack_ros
{

struct set_max_fps
{

typedef set_max_fpsRequest Request;
typedef set_max_fpsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct set_max_fps
} // namespace optitrack_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::optitrack_ros::set_max_fps > {
  static const char* value()
  {
    return "36dc21313a69becdf48c7c73a2375235";
  }

  static const char* value(const ::optitrack_ros::set_max_fps&) { return value(); }
};

template<>
struct DataType< ::optitrack_ros::set_max_fps > {
  static const char* value()
  {
    return "optitrack_ros/set_max_fps";
  }

  static const char* value(const ::optitrack_ros::set_max_fps&) { return value(); }
};


// service_traits::MD5Sum< ::optitrack_ros::set_max_fpsRequest> should match 
// service_traits::MD5Sum< ::optitrack_ros::set_max_fps > 
template<>
struct MD5Sum< ::optitrack_ros::set_max_fpsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::optitrack_ros::set_max_fps >::value();
  }
  static const char* value(const ::optitrack_ros::set_max_fpsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::optitrack_ros::set_max_fpsRequest> should match 
// service_traits::DataType< ::optitrack_ros::set_max_fps > 
template<>
struct DataType< ::optitrack_ros::set_max_fpsRequest>
{
  static const char* value()
  {
    return DataType< ::optitrack_ros::set_max_fps >::value();
  }
  static const char* value(const ::optitrack_ros::set_max_fpsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::optitrack_ros::set_max_fpsResponse> should match 
// service_traits::MD5Sum< ::optitrack_ros::set_max_fps > 
template<>
struct MD5Sum< ::optitrack_ros::set_max_fpsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::optitrack_ros::set_max_fps >::value();
  }
  static const char* value(const ::optitrack_ros::set_max_fpsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::optitrack_ros::set_max_fpsResponse> should match 
// service_traits::DataType< ::optitrack_ros::set_max_fps > 
template<>
struct DataType< ::optitrack_ros::set_max_fpsResponse>
{
  static const char* value()
  {
    return DataType< ::optitrack_ros::set_max_fps >::value();
  }
  static const char* value(const ::optitrack_ros::set_max_fpsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OPTITRACK_ROS_MESSAGE_SET_MAX_FPS_H
