// Generated by gencpp from file optitrack_ros/set_noise.msg
// DO NOT EDIT!


#ifndef OPTITRACK_ROS_MESSAGE_SET_NOISE_H
#define OPTITRACK_ROS_MESSAGE_SET_NOISE_H

#include <ros/service_traits.h>


#include <optitrack_ros/set_noiseRequest.h>
#include <optitrack_ros/set_noiseResponse.h>


namespace optitrack_ros
{

struct set_noise
{

typedef set_noiseRequest Request;
typedef set_noiseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct set_noise
} // namespace optitrack_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::optitrack_ros::set_noise > {
  static const char* value()
  {
    return "d0dc0d6fe692ff81fc934e461610f50f";
  }

  static const char* value(const ::optitrack_ros::set_noise&) { return value(); }
};

template<>
struct DataType< ::optitrack_ros::set_noise > {
  static const char* value()
  {
    return "optitrack_ros/set_noise";
  }

  static const char* value(const ::optitrack_ros::set_noise&) { return value(); }
};


// service_traits::MD5Sum< ::optitrack_ros::set_noiseRequest> should match 
// service_traits::MD5Sum< ::optitrack_ros::set_noise > 
template<>
struct MD5Sum< ::optitrack_ros::set_noiseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::optitrack_ros::set_noise >::value();
  }
  static const char* value(const ::optitrack_ros::set_noiseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::optitrack_ros::set_noiseRequest> should match 
// service_traits::DataType< ::optitrack_ros::set_noise > 
template<>
struct DataType< ::optitrack_ros::set_noiseRequest>
{
  static const char* value()
  {
    return DataType< ::optitrack_ros::set_noise >::value();
  }
  static const char* value(const ::optitrack_ros::set_noiseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::optitrack_ros::set_noiseResponse> should match 
// service_traits::MD5Sum< ::optitrack_ros::set_noise > 
template<>
struct MD5Sum< ::optitrack_ros::set_noiseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::optitrack_ros::set_noise >::value();
  }
  static const char* value(const ::optitrack_ros::set_noiseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::optitrack_ros::set_noiseResponse> should match 
// service_traits::DataType< ::optitrack_ros::set_noise > 
template<>
struct DataType< ::optitrack_ros::set_noiseResponse>
{
  static const char* value()
  {
    return DataType< ::optitrack_ros::set_noise >::value();
  }
  static const char* value(const ::optitrack_ros::set_noiseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OPTITRACK_ROS_MESSAGE_SET_NOISE_H
