// Generated by gencpp from file optitrack_ros/unset_logfile.msg
// DO NOT EDIT!


#ifndef OPTITRACK_ROS_MESSAGE_UNSET_LOGFILE_H
#define OPTITRACK_ROS_MESSAGE_UNSET_LOGFILE_H

#include <ros/service_traits.h>


#include <optitrack_ros/unset_logfileRequest.h>
#include <optitrack_ros/unset_logfileResponse.h>


namespace optitrack_ros
{

struct unset_logfile
{

typedef unset_logfileRequest Request;
typedef unset_logfileResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct unset_logfile
} // namespace optitrack_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::optitrack_ros::unset_logfile > {
  static const char* value()
  {
    return "0d79450287345aef3f3e331856b25242";
  }

  static const char* value(const ::optitrack_ros::unset_logfile&) { return value(); }
};

template<>
struct DataType< ::optitrack_ros::unset_logfile > {
  static const char* value()
  {
    return "optitrack_ros/unset_logfile";
  }

  static const char* value(const ::optitrack_ros::unset_logfile&) { return value(); }
};


// service_traits::MD5Sum< ::optitrack_ros::unset_logfileRequest> should match 
// service_traits::MD5Sum< ::optitrack_ros::unset_logfile > 
template<>
struct MD5Sum< ::optitrack_ros::unset_logfileRequest>
{
  static const char* value()
  {
    return MD5Sum< ::optitrack_ros::unset_logfile >::value();
  }
  static const char* value(const ::optitrack_ros::unset_logfileRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::optitrack_ros::unset_logfileRequest> should match 
// service_traits::DataType< ::optitrack_ros::unset_logfile > 
template<>
struct DataType< ::optitrack_ros::unset_logfileRequest>
{
  static const char* value()
  {
    return DataType< ::optitrack_ros::unset_logfile >::value();
  }
  static const char* value(const ::optitrack_ros::unset_logfileRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::optitrack_ros::unset_logfileResponse> should match 
// service_traits::MD5Sum< ::optitrack_ros::unset_logfile > 
template<>
struct MD5Sum< ::optitrack_ros::unset_logfileResponse>
{
  static const char* value()
  {
    return MD5Sum< ::optitrack_ros::unset_logfile >::value();
  }
  static const char* value(const ::optitrack_ros::unset_logfileResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::optitrack_ros::unset_logfileResponse> should match 
// service_traits::DataType< ::optitrack_ros::unset_logfile > 
template<>
struct DataType< ::optitrack_ros::unset_logfileResponse>
{
  static const char* value()
  {
    return DataType< ::optitrack_ros::unset_logfile >::value();
  }
  static const char* value(const ::optitrack_ros::unset_logfileResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OPTITRACK_ROS_MESSAGE_UNSET_LOGFILE_H
